### ISSUE TITLE
Error occurs when run 'sh train_job.sh'  with 1 TitanX (gpu:12GB)

### ISSUE THREAD

**Issue by zhangguanghui1** [lightaime/deep_gcns#2]
......

**** EPOCH 001 ****
----
Current batch/total batch num: 0/9949
2019-06-08 19:12:55.361276: E tensorflow/core/grappler/optimizers/dependency_optimizer.cc:666] Iteration = 0, topological sort failed with message: The graph couldn't be sorted in topological order.
2019-06-08 19:12:55.437713: E tensorflow/core/grappler/optimizers/dependency_optimizer.cc:666] Iteration = 1, topological sort failed with message: The graph couldn't be sorted in topological order.
2019-06-08 19:13:01.682376: E tensorflow/core/grappler/optimizers/dependency_optimizer.cc:666] Iteration = 0, topological sort failed with message: The graph couldn't be sorted in topological order.
2019-06-08 19:13:01.729082: E tensorflow/core/grappler/optimizers/dependency_optimizer.cc:666] Iteration = 1, topological sort failed with message: The graph couldn't be sorted in topological order.
2019-06-08 19:13:04.594699: E tensorflow/stream_executor/cuda/cuda_dnn.cc:363] Loaded runtime CuDNN library: 7.0.5 but source was compiled with: 7.1.4.  CuDNN library major and minor version needs to match or have higher minor version in case of CuDNN 7.0 or later version. If using a binary install, upgrade your CuDNN library.  If building from sources, make sure the library loaded at runtime is compatible with the version specified during compile configuration.
2019-06-08 19:13:04.595317: W ./tensorflow/stream_executor/stream.h:2093] attempting to perform DNN operation using StreamExecutor without DNN support
Traceback (most recent call last):
  File "/media/zgh/df7f0859-33fc-4a7e-afef-851b5c4f4005/zgh/runrunrun/pycharm-community-2019.1.1/helpers/pydev/pydevd.py", line 1741, in <module>
    main()
  File "/media/zgh/df7f0859-33fc-4a7e-afef-851b5c4f4005/zgh/runrunrun/pycharm-community-2019.1.1/helpers/pydev/pydevd.py", line 1735, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/media/zgh/df7f0859-33fc-4a7e-afef-851b5c4f4005/zgh/runrunrun/pycharm-community-2019.1.1/helpers/pydev/pydevd.py", line 1135, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/media/zgh/winz/3D/deep_gcns/sem_seg/train.py", line 333, in <module>
    train()
  File "/media/zgh/winz/3D/deep_gcns/sem_seg/train.py", line 275, in train
    train_one_epoch(sess, ops, train_writer)
  File "/media/zgh/winz/3D/deep_gcns/sem_seg/train.py", line 320, in train_one_epoch
    feed_dict=feed_dict)
  File "/media/zgh/df7f0859-33fc-4a7e-afef-851b5c4f4005/zgh/3D/.virtualenvs/py2te112/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/media/zgh/df7f0859-33fc-4a7e-afef-851b5c4f4005/zgh/3D/.virtualenvs/py2te112/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "/media/zgh/df7f0859-33fc-4a7e-afef-851b5c4f4005/zgh/3D/.virtualenvs/py2te112/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1328, in _do_run
    run_metadata)
  File "/media/zgh/df7f0859-33fc-4a7e-afef-851b5c4f4005/zgh/3D/.virtualenvs/py2te112/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
**tensorflow.python.framework.errors_impl.InternalError: cudnn PoolBackward launch failed**
	 [[node tower_0/gradients/tower_0/maxpool/maxpool_grad/MaxPoolGrad (defined at /media/zgh/winz/3D/deep_gcns/sem_seg/train.py:223)  = MaxPoolGrad[T=DT_FLOAT, data_format="NHWC", ksize=[1, 4096, 1, 1], padding="VALID", strides=[1, 2, 2, 1], _device="/job:localhost/replica:0/task:0/device:GPU:0"](tower_0/adj_conv_final/Relu, tower_0/maxpool/maxpool, tower_0/gradients/tower_0/Tile_28_grad/Sum)]]
	 [[{{node tower_0/gradients/AddN_147/_2879}} = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_19645_tower_0/gradients/AddN_147", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

Caused by op u'tower_0/gradients/tower_0/maxpool/maxpool_grad/MaxPoolGrad', defined at:
  File "/media/zgh/df7f0859-33fc-4a7e-afef-851b5c4f4005/zgh/runrunrun/pycharm-community-2019.1.1/helpers/pydev/pydevd.py", line 1741, in <module>
    main()
  File "/media/zgh/df7f0859-33fc-4a7e-afef-851b5c4f4005/zgh/runrunrun/pycharm-community-2019.1.1/helpers/pydev/pydevd.py", line 1735, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/media/zgh/df7f0859-33fc-4a7e-afef-851b5c4f4005/zgh/runrunrun/pycharm-community-2019.1.1/helpers/pydev/pydevd.py", line 1135, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/media/zgh/winz/3D/deep_gcns/sem_seg/train.py", line 333, in <module>
    train()
  File "/media/zgh/winz/3D/deep_gcns/sem_seg/train.py", line 223, in train
    grads = trainer.compute_gradients(loss)
  File "/media/zgh/df7f0859-33fc-4a7e-afef-851b5c4f4005/zgh/3D/.virtualenvs/py2te112/local/lib/python2.7/site-packages/tensorflow/python/training/optimizer.py", line 519, in compute_gradients
    colocate_gradients_with_ops=colocate_gradients_with_ops)
  File "/media/zgh/df7f0859-33fc-4a7e-afef-851b5c4f4005/zgh/3D/.virtualenvs/py2te112/local/lib/python2.7/site-packages/tensorflow/python/ops/gradients_impl.py", line 630, in gradients
    gate_gradients, aggregation_method, stop_gradients)
  File "/media/zgh/df7f0859-33fc-4a7e-afef-851b5c4f4005/zgh/3D/.virtualenvs/py2te112/local/lib/python2.7/site-packages/tensorflow/python/ops/gradients_impl.py", line 814, in _GradientsHelper
    lambda: grad_fn(op, *out_grads))
  File "/media/zgh/df7f0859-33fc-4a7e-afef-851b5c4f4005/zgh/3D/.virtualenvs/py2te112/local/lib/python2.7/site-packages/tensorflow/python/ops/gradients_impl.py", line 408, in _MaybeCompile
    return grad_fn()  # Exit early
  File "/media/zgh/df7f0859-33fc-4a7e-afef-851b5c4f4005/zgh/3D/.virtualenvs/py2te112/local/lib/python2.7/site-packages/tensorflow/python/ops/gradients_impl.py", line 814, in <lambda>
    lambda: grad_fn(op, *out_grads))
  File "/media/zgh/df7f0859-33fc-4a7e-afef-851b5c4f4005/zgh/3D/.virtualenvs/py2te112/local/lib/python2.7/site-packages/tensorflow/python/ops/nn_grad.py", line 607, in _MaxPoolGrad
    data_format=op.get_attr("data_format"))
  File "/media/zgh/df7f0859-33fc-4a7e-afef-851b5c4f4005/zgh/3D/.virtualenvs/py2te112/local/lib/python2.7/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 5081, in max_pool_grad
    data_format=data_format, name=name)
  File "/media/zgh/df7f0859-33fc-4a7e-afef-851b5c4f4005/zgh/3D/.virtualenvs/py2te112/local/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/media/zgh/df7f0859-33fc-4a7e-afef-851b5c4f4005/zgh/3D/.virtualenvs/py2te112/local/lib/python2.7/site-packages/tensorflow/python/util/deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "/media/zgh/df7f0859-33fc-4a7e-afef-851b5c4f4005/zgh/3D/.virtualenvs/py2te112/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 3274, in create_op
    op_def=op_def)
  File "/media/zgh/df7f0859-33fc-4a7e-afef-851b5c4f4005/zgh/3D/.virtualenvs/py2te112/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1770, in __init__
    self._traceback = tf_stack.extract_stack()

...which was originally created as op u'tower_0/maxpool/maxpool', defined at:
  File "/media/zgh/df7f0859-33fc-4a7e-afef-851b5c4f4005/zgh/runrunrun/pycharm-community-2019.1.1/helpers/pydev/pydevd.py", line 1741, in <module>
    main()
[elided 2 identical lines from previous traceback]
  File "/media/zgh/winz/3D/deep_gcns/sem_seg/train.py", line 333, in <module>
    train()
  File "/media/zgh/winz/3D/deep_gcns/sem_seg/train.py", line 204, in train
    skip_connect=SKIP_CONNECT)
  File "/media/zgh/winz/3D/deep_gcns/sem_seg/model.py", line 50, in __init__
    fusion = self.build_fusion_block(graphs, num_vertices)
  File "/media/zgh/winz/3D/deep_gcns/sem_seg/model.py", line 115, in build_fusion_block
    out_max = tf_util.max_pool2d(out, [num_vertices, 1], padding='VALID', scope='maxpool')
  File "/media/zgh/winz/3D/deep_gcns/utils/tf_util.py", line 381, in max_pool2d
    name=sc.name)
  File "/media/zgh/df7f0859-33fc-4a7e-afef-851b5c4f4005/zgh/3D/.virtualenvs/py2te112/local/lib/python2.7/site-packages/tensorflow/python/ops/nn_ops.py", line 2140, in max_pool
    name=name)
  File "/media/zgh/df7f0859-33fc-4a7e-afef-851b5c4f4005/zgh/3D/.virtualenvs/py2te112/local/lib/python2.7/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 4641, in max_pool
    data_format=data_format, name=name)
  File "/media/zgh/df7f0859-33fc-4a7e-afef-851b5c4f4005/zgh/3D/.virtualenvs/py2te112/local/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/media/zgh/df7f0859-33fc-4a7e-afef-851b5c4f4005/zgh/3D/.virtualenvs/py2te112/local/lib/python2.7/site-packages/tensorflow/python/util/deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "/media/zgh/df7f0859-33fc-4a7e-afef-851b5c4f4005/zgh/3D/.virtualenvs/py2te112/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 3274, in create_op
    op_def=op_def)
  File "/media/zgh/df7f0859-33fc-4a7e-afef-851b5c4f4005/zgh/3D/.virtualenvs/py2te112/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1770, in __init__
    self._traceback = tf_stack.extract_stack()

InternalError (see above for traceback): cudnn PoolBackward launch failed
	 [[node tower_0/gradients/tower_0/maxpool/maxpool_grad/MaxPoolGrad (defined at /media/zgh/winz/3D/deep_gcns/sem_seg/train.py:223)  = MaxPoolGrad[T=DT_FLOAT, data_format="NHWC", ksize=[1, 4096, 1, 1], padding="VALID", strides=[1, 2, 2, 1], _device="/job:localhost/replica:0/task:0/device:GPU:0"](tower_0/adj_conv_final/Relu, tower_0/maxpool/maxpool, tower_0/gradients/tower_0/Tile_28_grad/Sum)]]
	 [[{{node tower_0/gradients/AddN_147/_2879}} = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_19645_tower_0/gradients/AddN_147", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

We've got an error while stopping in post-mortem: <type 'exceptions.KeyboardInterrupt'>

Process finished with exit code 1

Could you help me? Thank you very much!

**Comment by lightaime** [comment]
It could be the problem of **tensorflow** or **cudnn**. Which versions are you using? I used **cudatoolkit 9.2** and **cudnn 7.3.1** for experiments. And try to reduce batch size if you have OOM issue.

Also refer to for [https://github.com/tensorflow/tensorflow/issues/13292](https://github.com/tensorflow/tensorflow/issues/13292) similar issues

**Comment by 16619884724** [comment]
I also encountered the same problem. I already reduce the batch size to 4.My CUDA is 9.0.176,CUDNN is 7.4.2 ,tensorflow is 1.12.0 ,python is 2.7.15 .This is a public environment, I can't modify it at this time.SO when can you  release the pytorch version?thank you
**** EPOCH 001 ****
----
Current batch/total batch num: 0/2490
2019-06-28 17:00:37.361377: E tensorflow/core/grappler/optimizers/dependency_optimizer.cc:666] Iteration = 0, topological sort failed with message: The graph couldn't be sorted in topological order.
2019-06-28 17:00:37.598152: E tensorflow/core/grappler/optimizers/dependency_optimizer.cc:666] Iteration = 1, topological sort failed with message: The graph couldn't be sorted in topological order.
2019-06-28 17:00:39.769279: E tensorflow/core/grappler/optimizers/dependency_optimizer.cc:666] Iteration = 0, topological sort failed with message: The graph couldn't be sorted in topological order.
2019-06-28 17:00:39.918069: E tensorflow/core/grappler/optimizers/dependency_optimizer.cc:666] Iteration = 1, topological sort failed with message: The graph couldn't be sorted in topological order.
2019-06-28 17:00:53.975939: W tensorflow/core/common_runtime/bfc_allocator.cc:267] Allocator (GPU_0_bfc) ran out of memory trying to allocate 512.00MiB.  Current allocation summary follows.
When can you  release the pytorch version?

**Comment by lightaime** [comment]
How big is the memory of you machine? It seems it is the problem of memory. Could you try to reduce the batch size to 1 or reduce the number of layer to see if this error still occurs.

**Comment by 16619884724** [comment]
Thank you very much, my GPU is 12GB. After listening to your suggestion, I changed the batchsize to 1, the layer number is still 28, then the same error occurred, so I changed the layer number to 14, now Normal operation, and by the way , I would like to ask, will the  paper release the pytorch version? when ? Thank you


------------------ 原始邮件 ------------------
发件人: "Guohao Li"<notifications@github.com>;
发送时间: 2019年7月4日(星期四) 晚上8:23
收件人: "lightaime/deep_gcns"<deep_gcns@noreply.github.com>;
抄送: "Confession"<1773507074@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [lightaime/deep_gcns] Error occurs when run 'sh train_job.sh' with 1 TitanX (gpu:12GB) (#2)




How big is the memory of you machine? It seems it is the problem of memory. Could you try to reduce the batch size to 1 or reduce the number of layer to see if this error still occurs.

**Comment by lightaime** [comment]
Thank you for your feedback. We plan to release a pytorch version. But it might take some time. We do not have an exact date yet.

**Comment by 16619884724** [comment]
Thank you and look forward to the release of pytorch version.谢谢


---Original---

**Comment by lightaime** [comment]
@16619884724 Hello, thanks for your interest in our work. The draft of Pytorch version Deep GCN is ready now. Please check our https://github.com/lightaime/deep_gcns_torch and feel free to ask any question.

**Comment by 16619884724** [comment]
Thank you very much.


 
---Original---
